function calling() {
    try {} catch (error) {
        throw "error";
    } finally {
        console.log("");
        console.log("");
        console.log("");
        console.log("");
    }
}